export const products = [
    {
        id: "gimm",
        name: "GIMM",
        fullName: "Gralix Investment Management Platform",
        description: "Comprehensive platform for investment portfolio tracking, real-time reporting, and IFRS 9 compliance.",
        features: [
            "Centralized investment tracking across multiple asset classes",
            "Automated IFRS 9 ECL calculations with staging",
            "Real-time portfolio analytics and dashboards",
            "Automated report generation for regulators",
        ],
        benefits: [
            "Reduce manual effort by 80% with automation",
            "Ensure regulatory compliance effortlessly",
            "Make data-driven investment decisions",
            "Scale from small portfolios to enterprise-level management",
        ],
    },
    {
        id: "ibnr",
        name: "IBNR",
        fullName: "Insurance Reserving Application",
        description: "Accurate IBNR reserve calculations using simplified actuarial methods, scenario analysis, and forecasting.",
        features: [
            "Chain Ladder, BF, and Cape Cod methods",
            "Scenario analysis and forecasting",
            "Automated quarterly/annual reporting",
            "Multi-currency support",
        ],
        benefits: [
            "Reduce actuarial processing time significantly",
            "Improve accuracy of reserve estimates",
            "Meet regulatory deadlines with confidence",
            "Transparent audit trail for all calculations",
        ],
    },
    {
        id: "ifrs-17",
        name: "IFRS 17",
        fullName: "IFRS 17 Compliance Application",
        description: "Seamless transition to the IFRS 17 standard with automated contract grouping, measurement, and disclosure.",
        features: [
            "Insurance contract valuation (BBA, PAA, VFA)",
            "CSM calculation and amortization",
            "Real-time financial statement impact analysis",
            "Seamless integration with existing actuarial systems",
        ],
        benefits: [
            "Achieve full IFRS 17 compliance",
            "Automate complex insurance contract accounting",
            "Gain clarity on profitability by contract group",
            "Reduce implementation risk with proven methodology",
        ],
    },
    {
        id: "ifrs-9-tool",
        name: "IFRS 9 Tool",
        fullName: "ECL Calculation Engine",
        description: "Robust Expected Credit Loss calculation engine compliant with IFRS 9 using advanced statistical models.",
        features: [
            "PD, EAD, LGD calculations under multiple approaches",
            "12-month and Lifetime ECL modeling",
            "Macroeconomic scenario overlay capability",
            "User-friendly dashboards with drill-down",
        ],
        benefits: [
            "Ensure IFRS 9 compliance across all financial instruments",
            "Improve credit risk management and provisioning",
            "Run multiple scenarios for stress testing",
            "Auditable model governance framework",
        ],
    },
    {
        id: "raidmercury",
        name: "RaidMercury",
        fullName: "Insurance Fraud Detection",
        description: "Advanced fraud detection and risk assessment using machine learning and behavioral analytics.",
        features: [
            "ML-powered fraud detection algorithms",
            "Risk scoring and anomaly detection",
            "Real-time alerts and case management",
            "Historical claims pattern analysis",
        ],
        benefits: [
            "Reduce fraudulent claims payouts",
            "Faster claims processing with automation",
            "Protect policyholders and the bottom line",
            "Continuously improving detection accuracy",
        ],
    },
    {
        id: "rubiclend",
        name: "RubicLend",
        fullName: "KYC & Loan Management",
        description: "End-to-end loan lifecycle management from customer onboarding to repayment with integrated KYC.",
        features: [
            "Digital onboarding with KYC verification",
            "Automated credit scoring and decisioning",
            "Loan disbursement and repayment tracking",
            "Collections management and notifications",
        ],
        benefits: [
            "Digitize the entire lending process",
            "Reduce loan processing time dramatically",
            "Improve borrower experience and satisfaction",
            "Ensure KYC/AML regulatory compliance",
        ],
    },
    {
        id: "kapitao",
        name: "Kapitao",
        fullName: "Real-Time Asset Flow",
        description: "Enterprise Fixed Asset Management System for end-to-end lifecycle tracking, depreciation, and reporting.",
        features: [
            "Complete asset lifecycle management",
            "Automated depreciation calculations",
            "QR/barcode scanning for physical verification",
            "Deep reporting and analytics dashboards",
        ],
        benefits: [
            "Total visibility over all organizational assets",
            "Eliminate ghost assets and reduce losses",
            "Automate financial reporting for fixed assets",
            "ERP-ready API integrations for seamless workflows",
        ],
    },
    {
        id: "g-re",
        name: "G-Re",
        fullName: "Re-insurance Application",
        description: "Streamlined reinsurance operations with automated treaty management, claims processing, and risk analysis.",
        features: [
            "Treaty and facultative reinsurance management",
            "Automated premium and claims accounting",
            "Cession and retrocession tracking",
            "Financial reporting and reconciliation",
        ],
        benefits: [
            "Streamline reinsurance administrative processes",
            "Improve accuracy of cession calculations",
            "Real-time view of reinsurance arrangements",
            "Faster claims recovery from reinsurers",
        ],
    },
];
